{% set name = "sendgrid" %}
{% set version = "6.1.0" %}
{% set file_ext = "tar.gz" %}
{% set hash_value = "cb0b21a83a54bc99d9befda1ea7b4f15fe8db362a152458e58abc5ce23d6d828" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: '{{ hash_value }}'

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - python_http_client >=3.0
    - pyyaml
    - six
    - werkzeug

test:
  imports:
    - sendgrid
    - sendgrid.helpers
    - sendgrid.helpers.inbound
    - sendgrid.helpers.mail

about:
  home: https://github.com/sendgrid/sendgrid-python/
  license: MIT
  license_family: MIT
  license_file: 'LICENSE.txt'
  summary: SendGrid library for Python
  description: "SendGrid Python library. This library allows you to quickly and easily use the SendGrid Web API v3 via Python"
  doc_url: 'https://github.com/sendgrid/sendgrid-python'
  dev_url: 'https://github.com/sendgrid/sendgrid-python'

extra:
  recipe-maintainers:
    - RohitK89
    - mariusvniekerk
