{% set name = "sendgrid" %}
{% set version = "6.12.5" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 'ea9aae30cd55c332e266bccd11185159482edfc07c149b6cd15cf08869fabdb7'

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - cryptography >=45.0.6
    # Note: do not use requirements.txt, which seems to be for development only
    # However, tests fail without this:
    - pyyaml >=4.2b1
    - python_http_client >=3.2.1
    - ecdsa >=0.19.1,<1
    # Using the most restrictive constraints for python >=3.12 here to stay noarch: python
    - werkzeug >=2.3.5

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - sendgrid
    - sendgrid.helpers
    - sendgrid.helpers.inbound
    - sendgrid.helpers.mail

about:
  home: https://github.com/sendgrid/sendgrid-python/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: SendGrid library for Python
  description: "SendGrid Python library. This library allows you to quickly and easily use the SendGrid Web API v3 via Python"
  doc_url: 'https://github.com/sendgrid/sendgrid-python'
  dev_url: 'https://github.com/sendgrid/sendgrid-python'

extra:
  recipe-maintainers:
    - RohitK89
    - mariusvniekerk
    - xylar
