{% set name = "sendgrid" %}
{% set version = "6.1.2" %}
{% set file_ext = "tar.gz" %}
{% set hash_value = "8112a3e2edd4cef208ed46335f058d2782397b395b96a472dcfd5e2618cf621b" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: '{{ hash_value }}'

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - python_http_client >=3.0
    - pyyaml
    - six
    - werkzeug

test:
  imports:
    - sendgrid
    - sendgrid.helpers
    - sendgrid.helpers.inbound
    - sendgrid.helpers.mail

about:
  home: https://github.com/sendgrid/sendgrid-python/
  license: MIT
  license_family: MIT
  license_file: 'LICENSE.txt'
  summary: SendGrid library for Python
  description: "SendGrid Python library. This library allows you to quickly and easily use the SendGrid Web API v3 via Python"
  doc_url: 'https://github.com/sendgrid/sendgrid-python'
  dev_url: 'https://github.com/sendgrid/sendgrid-python'

extra:
  recipe-maintainers:
    - RohitK89
    - mariusvniekerk
