{% set name = "sendgrid" %}
{% set version = "6.12.3" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 'd0cb7bf92cb5cc9fc4466074d6a40fd474332bbb52914a93620f566f26060ac7'

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    # from requirements.txt
    # this flask is super old but I'm going to trust it (for now...)
    - flask 1.1.2
    - pyyaml >=4.2b1
    - python_http_client >=3.2.1
    # losening six version requirement because it is otherwise not installable
    - six >=1.11.0
    - ecdsa >=0.19.1,<1
    # commenting out this dependency because it can't be installed and I
    # can't tell where it is needed
    # - more-itertools 5.0.0
    # Using the werkzeug constraints for python >=3.9,<3.11 here to stay noarch: python
    # Unfortunately, these are not compatible with the constraints for python >=3.11
    - werkzeug >=2.0.0,<3.0.0

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - sendgrid
    - sendgrid.helpers
    - sendgrid.helpers.inbound
    - sendgrid.helpers.mail

about:
  home: https://github.com/sendgrid/sendgrid-python/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: SendGrid library for Python
  description: "SendGrid Python library. This library allows you to quickly and easily use the SendGrid Web API v3 via Python"
  doc_url: 'https://github.com/sendgrid/sendgrid-python'
  dev_url: 'https://github.com/sendgrid/sendgrid-python'

extra:
  recipe-maintainers:
    - RohitK89
    - mariusvniekerk
    - xylar
